version: "3.0"
services:
  mongodb_3_4_1:
    image: mongo:3.4.16
    environment:
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_ROOT_USERNAME
    ports:
     - "3401:27017"
  mongodb_3_4_2:
    image: mongo:3.4.16
    environment:
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_ROOT_USERNAME
    ports:
     - "3402:27017"
  mongodb_3_4_3:
    image: mongo:3.4.16  
    environment:
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_ROOT_USERNAME
    ports:
     - "3403:27017"
  mongodb_3_4_4:
    image: mongo:3.4.16  
    environment:
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_ROOT_USERNAME
    ports:
     - "3404:27017"
  mongodb_3_4_5:
    image: mongo:3.4.16  
    environment:
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_ROOT_USERNAME
    ports:
     - "3405:27017"     
  mongodb_3_4_6:
    image: mongo:3.4.16  
    environment:
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_ROOT_USERNAME
    ports:
     - "3406:27017"     
  mongodb_3_4_7:
    image: mongo:3.4.16  
    environment:
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_ROOT_USERNAME
    ports:
     - "3407:27017"
  mongodb_3_4_8:
    image: mongo:3.4.16  
    environment:
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_ROOT_USERNAME
    ports:
     - "3408:27017"
  mongodb_3_4_9:
    image: mongo:3.4.16  
    environment:
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_ROOT_USERNAME
    ports:
     - "3409:27017"     
  mongodb_3_4_10:
    image: mongo:3.4.16  
    environment:
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_ROOT_USERNAME
    ports:
     - "3410:27017"         