version: "3.0"
services:
  mongodb_4_0_3:
    image: bitnami/mongodb:4.0.13
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGODB_REPLICA_SET_KEY=rplSet403
    ports:
     - "4003:27017" 
    restart: always      
  mongodb_4_0_4:
    image: bitnami/mongodb:4.0.13
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGODB_REPLICA_SET_KEY=rplSet404
    ports:
     - "4004:27017" 
    restart: always              
  mongodb_4_2_1:
    image: bitnami/mongodb:4.2.1
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGODB_REPLICA_SET_KEY=rplSet421
    ports:
     - "4201:27017" 
    restart: always      
  mongodb_4_2_2:
    image: bitnami/mongodb:4.2.0
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGODB_REPLICA_SET_KEY=rplSet422
    ports:
     - "4202:27017" 
    restart: always      
  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: Dockerfile
    environment:
      - RABBITMQ_DEFAULT_PASS=${MONGO_INITDB_ROOT_PASSWORD} 
    ports:
     - "15672:15672" 
     - "5672:5672" 
    restart: always      
    volumes:
      - /db/rabbitmq/mplay:/var/lib/rabbitmq/mnesia
      - /db/rabbitmq/mplay-plugins:/var/lib/rabbitmq/mnesia
      