version: "3.0"
services:
  mongodb_3_4_1:
    image: mongo:3.4.16
    environment:
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_ROOT_USERNAME
    ports:
     - "3401:27017"
    restart: always
  mongodb_3_4_2:
    image: mongo:3.4.16
    environment:
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_ROOT_USERNAME
    ports:
     - "3402:27017"
    restart: always
  mongodb_3_4_3:
    image: mongo:3.4.16  
    environment:
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_ROOT_USERNAME
    ports:
     - "3403:27017"
    restart: always   
  mongodb_3_4_4:
    image: mongo:3.4.16  
    environment:
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_ROOT_USERNAME
    ports:
     - "3404:27017"
    restart: always  
  mongodb_3_4_5:
    image: mongo:3.4.16  
    environment:
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_ROOT_USERNAME
    ports:
     - "3405:27017"  
    restart: always  
  mongodb_3_4_6:
    image: mongo:3.4.16  
    environment:
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_ROOT_USERNAME
    ports:
     - "3406:27017"   
    restart: always 
  mongodb_3_4_7:
    image: mongo:3.4.16  
    environment:
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_ROOT_USERNAME
    ports:
     - "3407:27017"
    restart: always 
  mongodb_3_4_8:
    image: mongo:3.4.16  
    environment:
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_ROOT_USERNAME
    ports:
     - "3408:27017"
    restart: always
  mongodb_3_4_9:
    image: mongo:3.4.16  
    environment:
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_ROOT_USERNAME
    ports:
     - "3409:27017"   
    restart: always  
  mongodb_3_4_10:
    image: mongo:3.4.16  
    environment:
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_ROOT_USERNAME
    ports:
     - "3410:27017" 
    restart: always 
  mongodb_3_6_1:
    image: mongo:3.6.6
    environment:
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_ROOT_USERNAME
    ports:
     - "3601:27017" 
    restart: always     
  mongodb_4_0_1:
    image: mongo:4.0.1 
    environment:
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_ROOT_USERNAME
    ports:
     - "4001:27017" 
    restart: always    
  mongodb_4_0_2:
    image: mongo:4.0.1 
    environment:
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_ROOT_USERNAME
    ports:
     - "4002:27017" 
    restart: always  
  mongodb_4_0_3:
    image: bitnami/mongodb:4.0.13
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGODB_REPLICA_SET_KEY=rplSet403
    ports:
     - "4003:27017" 
    restart: always      
  mongodb_4_0_4:
    image: bitnami/mongodb:4.0.13
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGODB_REPLICA_SET_KEY=rplSet404
    ports:
     - "4004:27017" 
    restart: always              
  mongodb_4_2_1:
    image: bitnami/mongodb:4.2.1
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGODB_REPLICA_SET_KEY=rplSet421
    ports:
     - "4201:27017" 
    restart: always      
  mongodb_4_2_2:
    image: bitnami/mongodb:4.2.0
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGODB_REPLICA_SET_KEY=rplSet422
    ports:
     - "4202:27017" 
    restart: always      
